SELECT 
    FI.ID AS ID
    ,FN.FISH_NAME AS FISH_NAME
    ,FI.LENGTH AS LENGTH
FROM 
    (SELECT 
        *
        ,DENSE_RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS R 
    FROM FISH_INFO) FI
    ,FISH_NAME_INFO FN 
WHERE 
    FI.FISH_TYPE = FN.FISH_TYPE
    AND FI.R = 1
ORDER BY 
    FI.ID ASC;

# SELECT 
#     *
#     ,DENSE_RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS R 
# FROM FISH_INFO